return {
    lute = {
        lint = {
            ruleconfigs = {
                divide_by_zero = {
                    severity = 'error',
                    off = false
                },

                duplicate_keys = {
                    severity = 'warn',
                    off = false
                },

                empty_if_block = {
                    severity = 'warn',
                    off = false
                },

                unused_variable = {
                    severity = 'warn',
                    off = false
                }
            },
        },
    },
}